//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inchiriere
    {
        public int id { get; set; }
        public string masinaid { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> pret { get; set; }
        public Nullable<System.DateTime> sdata { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
    }
}
