//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inrmasina
    {
        public int id { get; set; }
        public string nrmasina { get; set; }
        public string marca { get; set; }
        public string model { get; set; }
        public string disponibilitate { get; set; }
    }
}
