//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supermasinaEntities : DbContext
    {
        public supermasinaEntities()
            : base("name=supermasinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<inchiriere> inchiriere { get; set; }
        public virtual DbSet<inrmasina> inrmasina { get; set; }
        public virtual DbSet<returnaremasina> returnaremasina { get; set; }
        public virtual DbSet<Utilizator> Utilizator { get; set; }
    }
}
