//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnaremasina
    {
        public int id { get; set; }
        public string nrmasina { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> timptrecut { get; set; }
        public Nullable<int> amenda { get; set; }
    }
}
